materials:
  M_elements:
    - Li
    - Na
    - Mg
    - Al
    - Si
    - K
    - Ca
    - Sc
    - Ti
    - V
    - Cr
    - Mn
    - Fe
    - Co
    - Ni
    - Cu
    - Zn
    - Ga
    - Ge
    - Sr
    - Y
    - Zr
    - Nb
    - Mo
    - Rh
    - Pd
    - Ag
    - Cd
    - In
    - Sn
    - Ba
    - La
    - Ce
    - Pr
    - Nd
    - Sm
    - Gd
    - Tb
    - Dy
    - Ho
    - Er
    - Yb
    - Hf
    - Ta
    - W
    - Re
    - Os
    - Ir
    - Pt

  Ru_ratios:
    - 1.0
    - 0.8
    - 0.6
    - 0.4
    - 0.2
    - 0.0